POST http://localhost:3008/api/mascotas/
Content-Type : application/json

{
    "nombre": "kira",
    "raza": "Doberman",
    "edad": 2,
    "categoria": "Perro",
    "stateAdopcion": false,
    "refImg":1
}